CREATE SCHEMA IF NOT EXISTS keycloak;

GRANT ALL PRIVILEGES ON SCHEMA keycloak TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA keycloak TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA keycloak TO admin;

CREATE SCHEMA IF NOT EXISTS user_service;

GRANT ALL PRIVILEGES ON SCHEMA user_service TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA user_service TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA user_service TO admin;

ALTER USER admin SET search_path TO keycloak;